import { FEE_PERCENT as RISK_FEE_RATE } from "@tradejs/core/constants";
import {
  BacktestPriceMode,
  Direction,
  Interval,
  StrategyConfig,
} from "@tradejs/types";

export interface FlagSideConfig {
  enable: boolean;
  direction: Direction;
  minRiskRatio: number;
}

export type FlagEntryMode = "breakout" | "close_acceptance" | "retest";

export const config = {
  ENV: "BACKTEST",
  INTERVAL: "15" as Interval,
  MAKE_ORDERS: true,
  CLOSE_OPPOSITE_POSITIONS: false,
  BACKTEST_PRICE_MODE: "open" as const,
  AI_ENABLED: false,
  AI_MODE: "llm" as const,
  ML_ENABLED: false,
  ML_THRESHOLD: 0.1,
  MIN_AI_QUALITY: 4,
  RISK_FEE_RATE,
  RISK_SLIPPAGE_BPS: 0,
  RISK_MARKET_IMPACT_BPS: 0,
  MAX_LOSS_VALUE: 10,
  MA_FAST: 14,
  MA_MEDIUM: 49,
  MA_SLOW: 50,
  OBV_SMA: 10,
  ATR: 14,
  ATR_PCT_SHORT: 7,
  ATR_PCT_LONG: 30,
  BB: 20,
  BB_STD: 2,
  MACD_FAST: 12,
  MACD_SLOW: 26,
  MACD_SIGNAL: 9,
  FLAG_ATR_PERIOD: 14,
  FLAG_POLE_LOOKBACK_BARS: 12,
  FLAG_MIN_POLE_MOVE_PCT: 2,
  FLAG_MIN_POLE_MOVE_ATR: 3,
  FLAG_MIN_POLE_EFFICIENCY_RATIO: 0.6,
  FLAG_MIN_POLE_DIRECTIONAL_CONSISTENCY_RATIO: 0,
  FLAG_MIN_POLE_DIRECTIONAL_CONSISTENCY_RATIO_LONG: 0.85,
  FLAG_MIN_POLE_DIRECTIONAL_CONSISTENCY_RATIO_SHORT: 0,
  FLAG_MAX_POLE_TERMINAL_EXPANSION_RATIO: 0,
  FLAG_MAX_POLE_TERMINAL_EXPANSION_RATIO_LONG: 1.5,
  FLAG_MAX_POLE_TERMINAL_EXPANSION_RATIO_SHORT: 0,
  FLAG_POLE_TERMINAL_BARS: 3,
  FLAG_MIN_BARS: 6,
  FLAG_MAX_BARS: 30,
  FLAG_MAX_FLAG_TO_POLE_BARS_RATIO: 0,
  FLAG_MAX_FLAG_TO_POLE_BARS_RATIO_LONG: 0,
  FLAG_MAX_FLAG_TO_POLE_BARS_RATIO_SHORT: 0,
  FLAG_PIVOT_RADIUS: 1,
  FLAG_REQUIRE_FULL_PIVOT_NEIGHBORHOOD: true,
  FLAG_MIN_TOUCHES_PER_BOUNDARY: 3,
  FLAG_BOUNDARY_FIT_MODE: "least_squares" as const,
  FLAG_MIN_COUNTER_TREND_SLOPE_PCT_PER_BAR: 0.02,
  FLAG_MAX_SLOPE_DIVERGENCE_RATIO: 0.5,
  FLAG_MAX_CHANNEL_WIDTH_PCT: 2.5,
  FLAG_MAX_CHANNEL_WIDTH_ATR: 0,
  FLAG_MAX_CHANNEL_WIDTH_ATR_LONG: 0,
  FLAG_MAX_CHANNEL_WIDTH_ATR_SHORT: 0,
  FLAG_MAX_CHANNEL_TO_POLE_RATIO: 0.6,
  FLAG_MAX_FLAG_TO_POLE_VOLUME_RATIO: 0,
  FLAG_MAX_RETRACEMENT_RATIO: 0.7,
  FLAG_MAX_BOUNDARY_VIOLATION_ATR: 0.3,
  FLAG_BREAKOUT_BUFFER_ATR: 0.05,
  FLAG_MAX_BREAKOUT_DISTANCE_ATR: 1.5,
  FLAG_TARGET_POLE_RATIO: 1,
  FLAG_STOP_BUFFER_ATR: 0.25,
  FLAG_ENTRY_MODE: "close_acceptance" as FlagEntryMode,
  FLAG_CONFIRMATION_MAX_BARS: 2,
  FLAG_RETEST_MAX_BARS: 4,
  FLAG_RETEST_TOLERANCE_ATR: 0.25,
  FLAG_EXIT_ON_OPPOSITE_PATTERN: true,
  LONG: {
    enable: true,
    direction: "LONG",
    minRiskRatio: 0.7,
  },
  SHORT: {
    enable: true,
    direction: "SHORT",
    minRiskRatio: 0.7,
  },
} as const;

export type FlagConfig = StrategyConfig &
  Omit<
    typeof config,
    | "BACKTEST_PRICE_MODE"
    | "LONG"
    | "SHORT"
    | "MIN_AI_QUALITY"
    | "FLAG_REQUIRE_FULL_PIVOT_NEIGHBORHOOD"
  > & {
    BACKTEST_PRICE_MODE: BacktestPriceMode;
    MIN_AI_QUALITY: number;
    FLAG_ENTRY_MODE: FlagEntryMode;
    FLAG_REQUIRE_FULL_PIVOT_NEIGHBORHOOD: boolean;
    LONG: FlagSideConfig;
    SHORT: FlagSideConfig;
  };
